import Head from 'next/head';
import Card from '@/components/Card';
import Universe from '@/components/Universe';


export default function Home() {
  return (
    <>
      <Head>
        <title>Pokemon intern assignment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      <header className='hero-pattern pb-20'>
        <div className="container mx-auto px-2">
          <div className="logo py-10">
            <img className='text-center w-48 mx-auto' src={"./pokemon.png"} alt="Logo" />
          </div>
          <Card />
        </div>
      </header>



      <main className='container mx-auto px-2'>
        <Universe />
      </main>
    </>
  )


};





// import Head from 'next/head'
// // import Image from 'next/image'
// // import { Inter } from '@next/font/google'
// import React, { useState, useEffect } from 'react';


// const query = `
// query {
//   pokemons(limit: 20){
//     results {
//       id
//       url 
//       name 
//       image 
//       artwork 
//       dreamworld 
//     }
//   }
// }

// `;



// export default function Home() {

//   const [pokemons, setPokemons] = useState([]);

//   useEffect(() => {
//     fetch('https://graphql-pokeapi.graphcdn.app/', {
//       credentials: 'omit',
//       headers: { 'Content-Type': 'application/json' },
//       body: JSON.stringify({
//         query
//       }),
//       method: 'POST',
//     })
//       .then((res) => res.json())
//       .then((res) => setPokemons(res.data.pokemons.results));

//   }, []);


//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main>
//         <ul>
//           {pokemons?.map(pokemon => (
//             <div key={pokemon.name}>
//               <h3>{pokemon.name} </h3>
//               <img src={pokemon.image} alt="" />
//             </div>
//           ))}

//           <h1>HI next</h1>
//         </ul>
//       </main>
//     </>
//   )
// }

